front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-larioja-routing.module.ts

Se agregó protección de roles a las rutas del módulo **'Reportes provinciales'**, garantizando que solo los usuarios con roles específicos puedan acceder a esta ruta.
- ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE.
- PERSONAL_DE_ESTADISTICA.
Closes: #9

[Feature] added role protection to 'la rioja' reports

---

back-end/hospital-api/src/main/java/net/pladema/generalreports/service/impl/GeneralReportExcelServiceImpl.java
back-end/hospital-api/src/main/java/net/pladema/nursingreports/service/impl/NursingReportExcelServiceImpl.java
back-end/hospital-api/src/main/java/net/pladema/olderadultsreports/service/impl/OlderAdultsReportExcelServiceImpl.java
back-end/hospital-api/src/main/java/net/pladema/programreports/service/impl/ProgramReportExcelServiceImpl.java
back-end/hospital-api/src/main/java/net/pladema/reportformat/DateFormat.java

Se realizó una modificación del formato de las fechas en los reportes Excel generados en el módulo de Reportes Provinciales.
Se agregó un paquete llamado **reporformat** con una clase **DateFormat.java** en el cual se alojan los métodos necesarios para hacer la modificación del formato de fechas en los Excel generados en el módulo de Reportes Provinciales de HSI.
Se pidió modificar el formato por defecto que muestra la fecha recogida de la base de datos al formato **dd-mm-yyyy** . 
Se encontraron varios formatos, algunos de los cuales incluían la fecha y hora hasta en milisegundos, lo cual dificultaba la legibilidad y comprensión de los datos debido a su extensión.
**Reportes modificados**
- Reportes generales
- Reportes de enfermería
- Reportes del adulto mayor
- Reportes de programas …

Modificación de fechas en Reportes Provinciales

---

front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.html

En la casilla "Interpretación de puntaje" se realizó una mejora que permite visualizar el resultado final del cuestionario como "PERSONA PRE FRAGIL" y "PERSONA FRAGIL" con el color solicitado #2687c5 (Hex)
Color:
**Previamente a la mejora:**
**Resultado final:**
Close #38

Added functionality in question final

---

front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.html

Se agregó un salto de linea "br" dentro un "div" para extender el container que rodea al formulario, de tal manera mejora la visualización del mismo y aporta una vista agradable al usuario

Improves aesthetics a frail form

---

front-end/apps/projects/hospital/src/app/modules/api-rest/services/dengue-reports.service.ts
front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reporte-dengue/constants/dengue-report-types.ts
front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reporte-dengue/reporte-dengue.component.html
front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reporte-dengue/reporte-dengue.component.scss
front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reporte-dengue/reporte-dengue.component.ts
front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-larioja.component.html
front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-larioja.module.ts

Esta pull request introduce una nueva pestaña para los reportes de Epidemiología en el frontend de la aplicación. La pestaña se integra dentro del módulo de Reportes Provinciales existente.
Closes: #111 
1. Desarrollo de la pestaña de Epidemiología:
- Se creó una nueva pestaña dentro del módulo de Reportes Provinciales.
- Se diseñó la interfaz de usuario para la pestaña.
- Se implementó la lógica para la interacción del usuario con la pestaña, descartando la selección de fechas.
- Se incorporaron textos destacados a la interfaz dirigidos al usuario con el fin de exclarecer dudas con respecto a la restricción de las fechas y horario de generacón de los reportes.
2. Creación del servicio para recuperar reportes:
- Se desarrolló un servicio que se comunica con los 2 endpoints …

[Frontend] Reportes de Dengue

---

back-end/hospital-api/src/main/java/net/pladema/errata/common/dto/ErrataRequestDTO.java
back-end/hospital-api/src/main/java/net/pladema/errata/common/repository/ErrataRepository.java
back-end/hospital-api/src/main/java/net/pladema/errata/common/repository/entity/Errata.java
back-end/hospital-api/src/main/java/net/pladema/errata/general/endpoints/controller/ErrataController.java
back-end/hospital-api/src/main/java/net/pladema/errata/general/endpoints/service/ErrataService.java

This PR introduces two new endpoints to the API:
1. POST `/institution/{institutionId}/errata/create/`
2. GET `/institution/{institutionId}/document/{documentId}/errata`
**There's only one task left, which would be only allowing the creation of an errata only to the creator of the original -associated- document, but other than that, the endpoint works OK.**
- Add a new controller for the `POST /institution/{institutionId}/errata/create/` endpoint
- `institutionId` is the only route parameter, used for method authorization.
- This endpoint creates a new errata associated to a document.
- Request body contains the errata's `description` and the related document's `id`.
``` json
{
"description": "Hola mundo",
"documentId": 1
}
```
- Add a new controller for the `GET …

Feat: add POST and GET endpoints for the errata feature

---

back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/dto/UpdateResponseDTO.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/update/controller/UpdateQuestionnaireController.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/update/domain/service/UpdateQuestionnaireService.java

Este PR añade un nuevo endpoint para el tratamiento de cuestionarios y pruebas, el cuál permite modificar las respuestas asociadas a un cuestionario, ya sea por que estén ingresadas erróneamente, como por que faltaron agregar ciertas respuestas en la carga original: en este caso, el endpoint crea las respuestas faltantes adecuadamente.
Si no se halla una respuesta con la  enviada como parámetro, nos devuelve un código `500 - Internal server error` con la respuesta `Failed to update questionnaire: Couldn't find questionnaire response with id X`; en caso que actualice con éxito recibimos un `200 - OK` y el response body `Updated questionnaire successfully`
- `/institution/{institutionId}/questionnaire/{questionnaireResponseId}/update`
- `institutionId`
- `questionnaireResponseId`
En este …

Feat: create 'update questionnaire' PUT endpoint

---

back-end/hospital-api/src/main/java/net/pladema/errata/common/dto/ErrataRequestDTO.java
back-end/hospital-api/src/main/java/net/pladema/errata/common/repository/CustomDocumentRepository.java
back-end/hospital-api/src/main/java/net/pladema/errata/general/endpoints/service/ErrataService.java

This PR adds a filter to the errata registering endpoint, so that only the creator of the original document may register an errata related to this document. Now, the `POST` endpoint should be as so:
- Route: `/institution/{institutionId}/errata/create` (unchanged)
- Route parameter(s): `institutionId`
- Request body:
```json
{
"description": "string",
"documentId": 0,
"healthcareProfessionalId": 0
}
```
- Added a filter that retrieves the healthcare professional ID from the request body of the `POST` endpoint.
- Added a custom document repository (with a query that uses the retrieved healthcare professional ID), and modified the service and controller layers.

feat: add author-restricted filter to errata creation endpoint

---

back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getpdf/domain/service/GetQuestionnairePdfService.java

Se cambió el método para buscar personas de **findById()** a **findPersonByPatientId()**, arreglando el error 400 que devolvía el sistema al intentar descargar un cuestionario en pdf.
Endpoint: `institution/{institutionId}/questionnaire/{questionnaireResponseId}/get-pdf`
Sin issues relaciondas.

[Fix] change the repositoryPerson method

---

back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/domain/service/QuestionnaireUtilsService.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getall/domain/service/GetAllService.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getpdf/domain/service/GetQuestionnairePdfService.java
back-end/hospital-api/src/main/resources/templates/flavors/minsal/edmonton_reports.html
back-end/hospital-api/src/main/resources/templates/flavors/minsal/familybg_reports.html
back-end/hospital-api/src/main/resources/templates/flavors/minsal/frail_reports.html
back-end/hospital-api/src/main/resources/templates/flavors/minsal/physicalperformance_reports.html

This PR introduces a few formatting improvements to the HTML templates used for the PDF generation of the questionnaires response, as well as extracting a duplicate method used for getting a patient's full name as a string.
- Change header fields "Detalles del paciente" and "Detalles del profesional" to "Datos del paciente" and "Datos del profesional" for all the questionnaires, respectively.
- Change header field "Licencia" to "M.P." (matrícula profesional) for all the questionnaires.
- Removes the "meses" detail of the patient's age in the header.
- Change questionnaire title from "Nombre del cuestionario - Resultados de informe" to ""Nombre del cuestionario - Informe de resultados" for all the questionnaires.
- In the FRAIL report, change syntax to more appropiate one for an item of …

Fix: reports pdf formatting & extract code duplicate

---

back-end/hospital-api/src/main/java/net/pladema/errata/common/dto/ErrataRequestDTO.java
back-end/hospital-api/src/main/java/net/pladema/errata/general/endpoints/service/ErrataService.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/domain/service/QuestionnaireUtilsService.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/repository/entity/QuestionnaireResponse.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getall/controller/GetAllController.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getall/domain/service/GetAllService.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getpdf/domain/service/GetQuestionnairePdfService.java

This pull request introduces the following 4 changes to the API:
1. Change a variable name in the **Errata** request DTO to better reflect the parameter usage.
2. Fix the population of the context hashmap being used to populate the HTML templates of the questionnaires, specially the **healthcare professional name and their license number** (used in the download as PDF endpoint).
3. Fix the 'get all questionnaire responses' endpoint to properly expose the related **healthcare professional's details**.
For the previously stated changes, specifically:
1. The JSON request payload for the `POST` (create) errata endpoint now will look like this:
```json
{
"description": "string",
"documentId": 0,
"userId": 0
}
```
for further details of the errata feature, take a look at #113 and #121.
3. The …

Fix: questionnaires professional details' fetching

---

back-end/hospital-api/src/main/resources/templates/flavors/minsal/edmonton_reports.html
back-end/hospital-api/src/main/resources/templates/flavors/minsal/frail_reports.html
back-end/hospital-api/src/main/resources/templates/flavors/minsal/physicalperformance_reports.html

Este pull request introduce los siguientes cambios a la API:
1. Modificación de las secciones de **Resultado de evaluación** de las plantillas HTML para la generación y descarga de los archivos PDF de los cuestionarios.
2. Adición respectiva de cuatro registros a la base de datos que reflejan estos cambios, respectivamente 2 por tabla a las siguientes tablas:
- `minsal_lr_option` y 
- `minsal_lr_item_option`.
Este cambio normaliza las secciones finales de todos los cuestionarios a la hora de descarga sus PDF. También se corrigieron algunas `id` en la plantilla del cuestionario de **Desempeño físico de adulto mayor**.
Este cambio surge a raíz del cambio anterior, y es la creación de registros que permitan impactar el resultado de evaluación final, tanto la puntuación como la opción …

Feat: modify final sections of assessments HTML template to be the same

---

front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/ambulatoria.module.ts
front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/alert-dialog/alert-dialog.component.html
front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/alert-dialog/alert-dialog.component.scss
front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/alert-dialog/alert-dialog.component.ts
front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/get-physical-performance/get-physical-performance.component.ts
front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/get-edmonton/get-edmonton.component.ts
front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/get-frail/get-frail.component.ts

Se creó una alerta para la descarga de cuestionarios de Adulto Mayor. Esta alerta está diseñada para los casos en los que se quiera descargar un cuestionario de un paciente que aún no tiene registrado ninguno de estos en la base de datos.
- Se agregó un componente de alerta para la descarga de cuestionarios de Adulto Mayor.
- Se integró la alerta a los siguientes componentes:
- get-frail component.
- get-edmonton component.
- get-physical-performance component.

[Feature] add dialog alert for 'Adulto Mayor' questionnaires

---

front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.html
front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.ts

Se realizó el update en la id que envia los resultados "desempeño fisico alto" y "desempeño fisico bajo" en GET PDF

Fix result in desempeño fisico

---

front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.html
front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.ts

Se realizó un ajuste en la lógica encargada de sumar el puntaje del formulario de Edmonton. El error consistía en que las opciones con la respuesta "No" sumaban 1 punto, cuando en realidad debían calcular 0 puntos.
Se cambió de posición la consigna "Rendimiento funcional".

FIX edmonton

---

front-end/apps/projects/hospital/src/app/modules/api-rest/services/general-reports.service.ts
front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-generales/constants/general-report-types.ts
front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-generales/reportes-generales.component.ts

**Descripción**:  
Este pull request implementa el reporte de prescripciones de medicamentos en el módulo de reportes provinciales de HSI.  
**Tareas completadas**:  
1. Se ha implementado el endpoint para obtener los datos de prescripciones de medicamentos.  
2. Se ha integrado la funcionalidad en el frontend, permitiendo a los usuarios acceder y visualizar el nuevo reporte.  
3. La interfaz ha sido diseñada para ser intuitiva y coherente con el diseño existente.  
**Criterios de Aceptación**:  
- El reporte de prescripciones de medicamentos aparece en la lista de reportes generales.  
- Los datos se recuperan correctamente desde el backend y se muestran en el frontend.  
- La funcionalidad ha sido probada y validada.  
**Notas Adicionales**:  
Se recomienda revisar la documentación del …

[Frontend] Implementación del Reporte de Prescripciones de Medicamentos

---

back-end/app/src/main/resources/application-dev.properties
back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/controller/GeneralReportsController.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/repository/entity/QuestionnaireResponse.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/create/controller/CreateQuestionnaireController.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/create/domain/service/CreateQuestionnaireService.java
back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getpdf/domain/service/GetQuestionnairePdfService.java
back-end/hospital-api/src/main/resources/templates/flavors/minsal/edmonton_reports.html
back-end/hospital-api/src/main/resources/templates/flavors/minsal/familybg_reports.html
back-end/hospital-api/src/main/resources/templates/flavors/minsal/frail_reports.html
back-end/hospital-api/src/main/resources/templates/flavors/minsal/physicalperformance_reports.html

- Change the title of medicines prescription report inside the sheet as requested by @MaksMaks98 
- Add correct `institutionId` persisting for questionnaires **creation service**, as well as PDFs related modifications in **HTML templates**, **get pdf service** and **related entity**.
- This also involves adding the `institution_id` column to `minsal_lr_questionnaire_response` table via the following query (@DocOc98):
```pgsql
ALTER TABLE minsal_lr_questionnaire_response ADD COLUMN institution_id integer REFERENCES institution(id);
```
- `institution_id` is nullable to conform with already created questionnaire response, which would need their `institution_id`s to be modified manually (they're null)

Feat: institution in questionnaire & medicines prescription report title

---

back-end/hospital-api/src/main/resources/META-INF/orm.xml

Se cambió el nombre de la columna _headCircumference_ en el archivo orm.xml
Se cambió el alias de la columna _headCircumference_ a _headCircunference_ en la consulta SQL para el reporte de consultas de odontología.

[Fix] fix query OdontologyConsultationDetail

---

front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.component.html

2.30.2
Se corrigió el error de tipeo observado en el módulo de "Rutas provinciales" en la pestaña de "ASISTENCIALES".

[Fix] Corrección de error de tipeo en "Rutas provinciales - Asistenciales"

---

back-end/hospital-api/src/main/java/net/pladema/provincialreports/odontologicalreports/controller/OdontologicalReportsController.java
back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/controller/OlderAdultReportsController.java
back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/repository/GerontologicalAssessmentsConsultationDetail.java
back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/repository/OlderAdultReportsQueryFactory.java
back-end/hospital-api/src/main/java/net/pladema/provincialreports/olderadultsreports/service/OlderAdultReportsExcelService.java
back-end/hospital-api/src/main/java/net/pladema/provincialreports/reportformat/repository/ReportsRepositoryUtils.java
back-end/hospital-api/src/main/resources/META-INF/orm.xml

- This PR introduces the gerontological assessments report to the _older adults_ reports group. It's located in the following route:
- `olderadultsreports/{institutionId}/gerontological-assessments`
- `institutionId` as **route** parameter, and `fromDate` and `toDate` as request parameters (**YYYY-MM-DD** format)
- Allowed roles: `ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE`, `PERSONAL_DE_ESTADISTICA`
- The PR also fixes a wrong value used as a column header in the '**odontological procedures**' report
- Manual controller endpoint testing performed using Swagger
- Fixes #217

feat: add gerontological assessments report (query & code implementations)

---

back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/controller/GeneralReportsController.java
back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/repository/MedicinesPrescriptionConsultationDetail.java
back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/service/GeneralReportsExcelService.java
back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/controller/NursingReportsController.java
back-end/hospital-api/src/main/java/net/pladema/provincialreports/nursingreports/service/NursingReportsExcelService.java
back-end/hospital-api/src/main/resources/META-INF/orm.xml

This PR introduces the following changes:
- Add `prescription` column to **medicines prescription report** (**general** reports group)
- Fix `evolution` field being empty in **nursing outpatient report** (**nursing** reports group)
- Reorder some columns in **nursing outpatient report** to conform with the specified user story
- Manual controller endpoint testing performed using Swagger
- Fixes #215

Fix: nursing outpatient and medicines prescription

---

front-end/apps/projects/hospital/src/app/modules/api-rest/services/olderadult-reports.service.ts
front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-adultomayor/constants/olderadult-report-types.ts
front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-adultomayor/reportes-adultomayor.component.ts

2.30.2
Este pull request implementa la creación del reporte titulado “Evaluaciones gerontológicas” en la pestaña de “Adulto Mayor” del módulo de “Reportes provinciales de HSI”.
- **Integración de Endpoint:** Se ha añadido el endpoint proporcionado por el backend para obtener los datos necesarios para el reporte. Ruta: `olderadultsreports/{institutionId}/gerontological-assessments`
- **Tipo de Reporte:** Se ha especificado el tipo de reporte correspondiente a “Evaluaciones gerontológicas”. 
- **Método de Descarga:** Se ha implementado el método para la descarga del archivo en formato Excel.
**Archivos afectado:** [olderadult-report-types.ts], [reportes-adultomayor.component.ts], [olderadult-reports.service.ts]
Closes: #222
**getOlderAdultsHospitalizationReport():** Método para llamar al …

[Frontend] Incorporación del reporte 'Escalas de Evalución Gerontológica'

---

back-end/hospital-api/src/main/java/net/pladema/emergencycareannex/controller/AnnexInECEController.java
back-end/hospital-api/src/main/java/net/pladema/emergencycareannex/domain/service/AnnexInECEService.java
back-end/hospital-api/src/main/resources/templates/flavors/minsal/annex_in_ece.html

What this PR does:
- Adds an endpoint to download **annex** document with data from `emergency_care_episode` and related tables
- Creates an HTML replica of the original **annex** document, with placeholders for nullable values
- Manual controller endpoint testing performed using Swagger UI
- `/institution/{institutionId}/emergency-care/episodes/{episodeId}/annex-pdf` - **GET**
- `institutionId` - integer
- `episodeId` - integer
- `Authorization`
```bash
curl -X 'GET' \
'http://localhost:8080/api/institution/1/emergency-care/episodes/1/annex-pdf' \
-H 'accept: */*' \
-H 'Authorization: Bearer [token]'
```
- Downloads a **PDF** file with the name "**Anexo II - Guardia - ID [episodeId]**"
- The data (if non-null) that populates the HTML template is the following:
- institutionName
- …

Feat: annex in emergency care ("guardia")
