Historia-Clinica-La-Rioja/historia_clinica_LR

- back-end/hospital-api/src/main/resources/templates/fragments/annex_report.html
Se modificó el informe de **Anexo II**, quitando la sección del PDF correspondiente a datos de empresas.
Closes: #15
> [Feature] modified Annex II report

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/routes/ambulatoria-paciente/ambulatoria-paciente.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/routes/ambulatoria-paciente/ambulatoria-paciente.component.ts
Este Pull Request aborda la tarea de agregar una condición de visibilidad en la pestaña "Adulto mayor" dentro de la sección de Historia clínica. La tarea requería que se implementara una condición que permitiera que solo los pacientes mayores de 60 años tengan acceso y visualización a esta pestaña específica.
Para lograr esto, se ha introducido una condición de visibilidad que verifica la edad del paciente. Ahora, la pestaña "Adulto mayor" solo estará disponible y será visible para los pacientes cuya edad sea igual o mayor a 60 años. Esta implementación garantiza que la información relevante en la pestaña esté reservada exclusivamente para este grupo de pacientes, mejorando así la experiencia y relevancia de la funcionalidad para los usuarios finales.
> Agregada condición de visibilidad …
> Filtro de edad/Age Filter

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.ts
Se realizo fix de formulario de escala de frail que lanzaba un error 400 al momento de enviar el test.
> Ahora el formulario se envia con exito y lanza un STATUS 200 (OK)
Closes #27 
____________________________________________________________________________________________-
A fix was made to the friar scale form that was throwing a 400 error when sending the test.
> Now the form is sent successfully and issues a STATUS 200 (OK)
Closes #27
> FIXED JSON FRAIL SCALE 

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.html
Se realizó el cambio de titulos para botones de adulto mayor:
>  "Agregar estudio" por ""Agregar evaluación."
>  "Ver ultimo estudio" por "Ver ultima evaluación."`
Antes:
Despues:
Issues relacionados:
Close #30
___________________________________________________________________________________________________
Changed titles for senior buttons:
> "Add study" by ""Add evaluation."
> "See latest study" for "See latest evaluation."`
Before:
After:
Close #30
> FIXED - Agregar evaluacion y Ver ultima evaluacion

- back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/controller/PregnantPeopleReportController.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/repository/PregnantAttentionsConsultationDetail.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/repository/PregnantControlsConsultationDetail.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/repository/PregnantPeopleReportQueryFactory.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/service/PregnantPeopleReportExcelService.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/pregnantpeoplereports/service/impl/PregnantPeopleReportExcelServiceImpl.java
- back-end/hospital-api/src/main/resources/META-INF/orm.xml
Se agregaron los reportes de personas gestantes al backend de la aplicación.
Se agregaron los siguientes reportes al módulo de **personas gestantes**:
- Atenciones a personas gestantes.
- Control de personas gestantes.
- **Atenciones a personas gestantes**: `/pregnantpeoplereports/{institutionId}/pregnant-attentions`
- **Parámetros**:
- **institutionId** (Integer): ID de la institución que solicita el reporte.
- **fromDate** (String): Fecha desde la cuál se quiere obtener el reporte.
- **toDate** (String): Fecha hasta la cuál se quiere obtener el reporte.
- **Roles con acceso**:
- _ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE_.
- _PERSONAL_DE_ESTADISTICA_.
- **Control de personas gestantes**: `/pregnantpeoplereports/{institutionId}/pregnant-controls`
- **Parámetros**:
- **institutionId** …
> [Feature] added pregnant people reports to backend

- front-end/apps/projects/hospital/src/app/modules/api-rest/services/pregnantpeople-reports.service.ts
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-larioja.component.html
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-larioja.module.ts
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-personagestante/constants/pregnantpeople-report-types.ts
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-personagestante/reportes-personagestante.component.html
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-personagestante/reportes-personagestante.component.scss
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-personagestante/reportes-personagestante.component.ts
Se agregaron los reportes de personas gestantes al frontend de la aplicación.
- Se creó la pestaña **PERSONA GESTANTE** en el módulo de **Reportes Provinciales**.
- Se agregaron las siguientes opciones en la lista desplegable de la pestaña **PERSONA GESTANTE:**
- Atenciones a personas gestantes.
- Control de personas gestantes.
- Cada una de las opciones disponibles en la lista desplegable, permiten descargar los respectivos reportes a los que hacen referencia.
Los siguientes roles contarán con acceso a la vista de los reportes para personas gestantes:
- _ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE_.
- _PERSONAL_DE_ESTADISTICA_.
Closes: #45 
Closes: #46 
Closes: #48
> [Feature] added pregnant people reports to frontend

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/tabla-sap/tabla-sap.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/tabla-sap/tabla-sap.component.scss
Se solucionaron bugs visuales en la pestaña **CRECIMIENTO FISICO (SAP)** de la sección **Historia Clínica**.
- Se corrigieron algunos bugs visuales a la hora de visualizar las diferentes tablas de crecimiento físico.
- Se cambió el subtítulo de la pestaña **CRECIMIENTO FISICO (SAP)**
- El subtítulo paso de _Tabla antropométrica_ a _Tablas Antropométricas_.
- Se hicieron correcciones de formato a nivel de código.
> [Fix] updated 'sap-table' section

- back-end/pom-parent.xml
Se ajustó la revisión del proyecto a la versión **2.8.11**
> [Feature] update configuration for 2.8.11 release

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.scss
Se realizaron los siguientes cambios:
Ahora cuando se desliza la flecha por encima, se activa un background color transparente siguiendo la interfaz general de HSI:
Se extiende cuadro de seleccion al momento de hacer click:
Ademas, se realizó:
> Se eliminaron lineas de codigo innecesarios que no afectan al funcionamiento de los botones.
> Se agregaron lineas para reestructurar los titulos de cada botón para una formación simetrica.
Estos cambios fueron solicitados a fines de una mejora visual para el usuario.
Closed #84
> Added features visual in evaluacion geriatricas

- front-end/apps/projects/hospital/src/app/modules/turnos/dialogs/confirm-booking/confirm-booking.component.ts
Se corrigió un fix en el que el diálogo **CancelAppointmentComponent** recibía los datos incorrectos al abrirse.
- Se corrigió un error a la hora de pasar los datos al cuadro de diálogo **CancelAppointmentComponent**.
> [Fix] data format fixed in CancelAppointmentComponent dialog

- back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/controller/GeneralReportController.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/repository/EmergencyConsultationDetail.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/generalreports/service/impl/GeneralReportExcelServiceImpl.java
- back-end/hospital-api/src/main/resources/META-INF/orm.xml
Se actualizó el reporte de **Emergencias** correspondiente a los **reportes generales**, agregando nuevos campos.
- Se agregaron al reporte de **Emergencias** los siguientes campos:
- Motivos.
- Problemas.
- Evolución.
Closes: #109
> [Feature] update emergency report

- back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/controller/EpidemiologyReportController.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/repository/CompleteDengueConsultationDetail.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/repository/DenguePatientControl.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/repository/DenguePatientControlConsultationDetail.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/repository/EpidemiologyReportQueryFactory.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/service/EpidemiologyReportExcelService.java
- back-end/hospital-api/src/main/java/net/pladema/provincialreports/epidemiologyreports/service/impl/EpidemiologyReportExcelServiceImpl.java
- back-end/hospital-api/src/main/resources/META-INF/orm.xml
Se agregaron dos reportes de **Epidemiología** al **backend** de la aplicación, específicamente en el módulo de  **Reportes Provinciales**.
Se agregaron los siguientes reportes de epidemiología:
- Atenciones Relacionadas con Dengue: **Control de pacientes**.
- Atenciones Relacionadas con Dengue: **Consultas completas**.
1. **Control de pacientes**: `/epidemiologyreports/{institutionId}/dengue-patient-control`
- **Parámetros**:
- **institutionId** (Integer): ID de la institución que solicita el reporte.
- **Roles con acceso**:
- _ADMINISTRADOR_INSTITUCIONAL_BACKOFFICE_.
- _PERSONAL_DE_ESTADISTICA_.
2. **Consultas completas**: `/epidemiologyreports/{institutionId}/complete-dengue`
- **Parámetros**:
- **institutionId** (Integer): ID de la institución que solicita el reporte.
- **Roles con …
> [Feature] add epidemiology reports

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.ts
1. Se reestructuro completamente sweet alert de onSubmit() para que en el caso de quedarse sin conexion a internet, el formulario indique el mensaje de "error".
2. Cambios minimos: correción de titulo "Contingencia" al correcto "Continencia".
closed #74
> Feature and fix endmonton form

- back-end/pom-parent.xml
Se ajustó la revisión del proyecto a la versión **2.16.3**
> [Feature] update configuration for 2.16.3 release

- back-end/pom-parent.xml
Se ajustó la revisión del proyecto a la versión 2.16.4
> [Feature] update configuration for 2.16.4 release

- back-end/pom-parent.xml
Se ajustó la revisión del proyecto a la versión 2.16.5
> [Feature] update configuration for 2.16.5 release

- back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/repository/QuestionnaireResponseRepository.java
- back-end/hospital-api/src/main/java/net/pladema/questionnaires/common/repository/entity/QuestionnaireResponse.java
- back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getall/controller/GetAllController.java
- back-end/hospital-api/src/main/java/net/pladema/questionnaires/general/getall/domain/service/GetAllService.java
Se agregó al controlador que devuelve todos los cuestionarios de un paciente, el campo _questionnaireResult_, para mostrar el resultado final de dichos cuestionarios.
- Se agregó el campo _questionnaireResult_ a la entidad QuestionnaireResponse.
- Se creó la lógica para obtener el resultado final del cuestionario y cargarla en el controlador.
> [Feature] update 'get-all-questionnaires' controller

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.scss
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.ts
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.ts
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.ts
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.ts
- Se añade la prueba corta de desempeño fisico a la interfaz de Adulto Mayor.
Vista previa:  
- La interfaz de la pestaña de Adulto Mayor ha sido actualizada. Ahora, los tres formularios más recientes creados para el paciente se visualizan utilizando el método multicolor "semáforo".
Los formularios disponibles para operar son:
> - Escala de Fragilidad de Edmonton
> - Escala de Frail
> - Prueba corta de desempeño fisico
Vista previa:
________________________________________________________________________________________-
- Se añadió el componente "app-no-data" para mostrar un mensaje que avisa al usuario cuando no hay formularios creados para el paciente.
_________________________________________________________________________________-
- Ahora al crear un formulario se actualiza la …
> Desempeño fisico y nueva interface

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/routes/ambulatoria-paciente/ambulatoria-paciente.component.html
Se efectuaron los cambios solicitados solicitados en la pestaña de "Adulto mayor", precisamente en el cuestionario denominado "Prueba corta de desempeño físico".
Dicho cuestionario se encuentra habilitado para pacientes de 60 años o más.
Close: #153 
1. El enunciado que se presenta actualmente al comienzo del cuestionario, con tipografía roja se modificó.
2. Se agregó el texto faltante en la sección “C. Pararse en posición tándem”.
3. Se retiró el texto “(Máx.15)” en las casillas para colocar el tiempo en segundos” (a exepción de la sección “C.Pararse en posición tándem”).
4. Se modificó el título “Levantarse de una silla” en la última sección del cuestionario.
> [ Fix ] Modificación de textos en cuestionario "Desempeño físico"

- back-end/pom-parent.xml
Se ajustó la revisión del proyecto a la versión 2.21.8
> [Feature] update configuration for 2.21.8 release

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/edmonton/edmonton.component.ts
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/frail-scale/frail-scale.component.ts
Se realiza el fix de visualización de puntaje para formularios de frail y edmonton según lo solicitado en la Issues  #163
closed #163
> FIX VISUALIZACION DE PUNTAJE - FRAIL/EDMONTON

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/emergente/inicio-estudio/inicio-estudio.component.scss
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.scss
Se realiza cambios y fix en los siguientes:
> - Ahora los titulos ya no son interactuables. 
> - Se quita la barra "overlay" de la parte inferior de la pestaña para mejorar visualización del inicio .
> - Se arregló el bug donde el radio button de la tercera opcion estaba sobrepuesto en el texto de la consigna.
Closed #165
Closed #164 
Closed #166 
______________________________________________________________
> FIX ADULTO MAYOR Y TEXTO DE DESEMPEÑO FISICO

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.scss
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/desempeno-fisico.component.ts
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/input-desempeno/input-desempeno.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/cuestionarios/desempeno-fisico/input-desempeno/input-desempeno.component.ts
Este pull request responde y cierra la issue #154 con las siguientes correcciones en el cuestionario "Prueba corta de desempeño físico" para la pestaña "Adulto Mayor" en la historia clínica de pacientes mayores de 60 años:
**1. Límites de tiempo:**
Se han establecido límites superiores e inferiores para los campos de ingreso de tiempo en segundos, de acuerdo a la imagen de referencia proporcionada.
**2. Habilitación condicionada del campo para ingreso del tiempo:**
Se ha modificado la lógica para controlar la visualización del campo de ingreso de tiempo en la sección "Velocidad de marcha- recorrido de 4 metros".
- El campo de ingreso de tiempo ahora se muestra solo después de seleccionar la opción "Accede a la prueba".
- El campo de ingreso de tiempo se posiciona debajo de las opciones de …
> [ Fix ] Correcciones en cuestionario "Prueba corta de desempeño físico" - Adulto Mayor - Limites de tiempo

- back-end/pom-parent.xml
Se ajustó la revisión del proyecto a la versión 2.21.9
> [Feature] update configuration for 2.21.9 release

- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/application/fetchconsultationsbysisacode/FetchConsultationsBySisaCode.java
- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/application/fetchimmunizationsbysisacode/FetchImmunizationsBySisaCode.java
- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/application/fetchrecipesbysisacode/FetchRecipesBySisaCode.java
- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/application/port/out/ConsultationDetailDataStorage.java
- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/domain/ImmunizationsDetailBo.java
- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/domain/RecipeDetailBo.java
- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/infrastructure/input/rest/SumarApiController.java
- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/infrastructure/input/rest/dto/ImmunizationsDetailDto.java
- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/infrastructure/input/rest/dto/RecipeDetailDto.java
- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/infrastructure/input/rest/mapper/ImmunizationsMapper.java
- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/infrastructure/input/rest/mapper/RecipeMapper.java
- back-end/hospital-public-api/src/main/java/ar/lamansys/sgh/publicapi/apisumar/infrastructure/output/ConsultationDetailDataStorageImpl.java
Se actualizó la api pública de SUMAR, agregando dos nuevos endpoints, uno para recetas, y otro para inmunizaciones. Además, se agregaron nuevos parámetros en la url de los endpoints, para poder especificar un rango de fechas a consultar.
- Se agregó un nuevo endpoint para buscar las inmunizaciones correspondientes a una institución.
- Se agregó un nuevo endpoint para buscar las recetas correspondientes a una institución.
- Se agregaron los parámetros _fromDate_ y _toDate_ a todos los endpoints.
> [Feature] update sumar public-api

- back-end/pom-parent.xml
Se ajustó la revisión del proyecto a la versión 2.21.10
> [Feature] update configuration for 2.21.10 release

- front-end/apps/projects/hospital/src/app/modules/api-rest/services/general-reports.service.ts
- front-end/apps/projects/hospital/src/app/modules/api-rest/services/nursing-reports.service.ts
- front-end/apps/projects/hospital/src/app/modules/api-rest/services/odontology-reports.service.ts
- front-end/apps/projects/hospital/src/app/modules/api-rest/services/olderadult-reports.service.ts
- front-end/apps/projects/hospital/src/app/modules/api-rest/services/pregnantpeople-reports.service.ts
- front-end/apps/projects/hospital/src/app/modules/api-rest/services/program-reports.service.ts
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-adultomayor/reportes-adultomayor.component.ts
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-enfermeria/reportes-enfermeria.component.ts
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-generales/reportes-generales.component.ts
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-odontologia/reportes-odontologia.component.ts
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-personagestante/reportes-personagestante.component.ts
- front-end/apps/projects/hospital/src/app/modules/reportes-larioja/reportes-programas/reportes-programas.component.ts
Se fixearon los reportes provinciales para evitar el uso de "Moment".
- Se actualizaron los siguientes reportes provinciales:
- Programas.
- Generales.
- Enfermería.
- Odontología.
- Adulto Mayor.
- Persona Gestante.
- Además, se actualizaron los servicios correspondientes a dichos reportes, para evitar el uso de "moment".
> [Feature] fix provincial reports in frontend

- front-end/apps/projects/hospital/src/app/modules/api-rest/api-model.d.ts
- front-end/apps/projects/hospital/src/app/modules/api-rest/services/antecedentes.service.ts
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/ambulatoria.module.ts
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.scss
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.ts
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/routes/ambulatoria-paciente/ambulatoria-paciente.component.html
Se ha implementado el formulario de antecedentes familiares en el cual los datos relacionados con la familia se envían correctamente a la base de datos. La funcionalidad actual garantiza que la información capturada en el formulario se procese y almacene con éxito en el backend.
La misma se ubica despues de la pestaña de Odontologia.
> BACKGROUNDS FAMILY FORM

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/routes/ambulatoria-paciente/ambulatoria-paciente.component.ts
Se actualizó el requerimiento de pestaña de ADULTO MAYOR, donde solo era visible para pacientes > 60 años, ahora es visible para >= 60 años.
closed #190
> CHANGE REQUERIMENTS AGE ADULTO MAYOR

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.scss
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.ts
Se realizan fix y mejoras en el formulario de antecedentes familiares, las mismas solicitados por QA testing.
**## issues relationated:**
closed #197
closed #198
closed #199 
closed #200
> FIX AND FEATURES BACKGROUNDS FAMILY

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/components/nota-de-evolucion-dock-popup/nota-de-evolucion-dock-popup.component.ts
Se cambió el formato de la fecha del procedimiento en la nota de evolución.
- Se cambió el formato de fecha de formato **YYYY-MM-DDTHH:MM.SSSZ** a **YYYY-MM-DD**.
> [Fix] data format fixed in evolution note popup

- back-end/hospital-api/src/main/resources/templates/flavors/minsal/familybg_reports.html
- Refactor back end code of the **family background** HTML template for the PDF download.
To make the visuals conform with the guidelines created by @MaksMaks98 
- Manual testing performed for back end endpoints via _Swagger UI_.
- Sample PDF download with the updated template: [CORDOBA GONZALO VICTOR - 24-05-2024 - Antecedentes Familiares y Determinantes Sociales.pdf](https://github.com/user-attachments/files/17116362/CORDOBA.GONZALO.VICTOR.-.24-05-2024.-.Antecedentes.Familiares.y.Determinantes.Sociales.pdf)
> feat: update family background questionnaire html template

- back-end/pom-parent.xml
Se ajustó la revisión del proyecto a la versión 2.24.9
> [Feature] update configuration for 2.24.9 release

- back-end/pom-parent.xml
Se ajustó la revisión del proyecto a la versión 2.24.10
> [Feature] update configuration for 2.24.10 release

- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.html
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/components/background-family/background-family.component.ts
- Se ha incorporado un campo de tipo "número" faltante en la sección "Madre" para ingresar la edad.
- Se ha implementado validación de entrada en los campos numéricos para restringir la inserción de caracteres especiales. Los intentos de ingresar signos como "-" o "+" resultarán en el borrado del valor ingresado.
- Se han homogeneizado los estilos de los campos de "Hermanos" para asegurar una apariencia consistente.
closed issues:
#199
> [Fix]. ANTECEDENTES 

- back-end/clinic-history/src/main/java/ar/lamansys/sgh/clinichistory/domain/ips/services/LoadMedication.java
- back-end/clinic-history/src/test/java/ar/lamansys/sgh/clinichistory/infrastructure/application/ips/CreateMedicationServiceImplTest.java
- back-end/hospital-api/src/main/java/net/pladema/clinichistory/requests/medicationrequests/infrastructure/input/rest/exception/MedicationRequestExceptionHandler.java
- back-end/hospital-shared/src/main/java/ar/lamansys/sgh/shared/domain/medicationrequestvalidation/MedicationRequestValidationDispatcherSenderBo.java
- back-end/interoperability/src/main/java/net/pladema/medicationrequestvalidation/infrastructure/output/MedicationRequestValidationPortImpl.java
- back-end/interoperability/src/main/java/net/pladema/medicationrequestvalidation/infrastructure/output/config/MedicationRequestValidationRestClient.java
- back-end/interoperability/src/main/java/net/pladema/medicationrequestvalidation/infrastructure/output/config/MedicationRequestValidationWSConfig.java
- back-end/pom-parent.xml
- front-end/apps/projects/hospital/src/app/modules/historia-clinica/modules/ambulatoria/modules/indicacion/dialogs/nueva-prescripcion/nueva-prescripcion.component.ts
Update the **development** branch to version **2.36.2**.
> [Update] Merge branch 'branch-2.36.2' into 'development'

- front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.component.html
- front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.component.scss
- front-end/apps/projects/hospital/src/app/modules/rutas-larioja/rutas.component.ts
2.36.0
Este Pull Request aborda la solicitud de unificación de las pestañas "ASISTENCIALES" y "PREVENTIVAS" del módulo "Rutas Provinciales". La intención es mejorar la experiencia del usuario al consolidar ambas pestañas en una única ventana de visualización.
- Unificación de Interfaces: Se ha creado una nueva interfaz que combina las funcionalidades y la información de ambas pestañas en una sola ventana.
- Se modificado el texto del ítem número 7 "Sonríe" por el texto "Enfermedades Infectocontagiosas", por solicitud del area pertinente.
closes: #239
> [Feature] Reestructuración de Rutas Provinciales
